### ISSUE TITLE
Rust fails to build on v5.13 ThinLTO

### ISSUE THREAD

**Issue by TheSven73** [Rust-for-Linux/linux#372]
- Grab #370 
- target a ThinLTO supported architecture (e.g. arm64)
- set `LLVM_IAS=1` so ThinLTO becomes selectable
- use general arm64 defconfig (`make defconfig`)
- in `defconfig` enable `CONFIG_LTO_CLANG_THIN`
- verify that everything builds
- now enable Rust in `defconfig`
- build errors are generated:

<details><summary><strong>Output</strong></summary>
<p>

```
$ make -j16 Image.gz
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  RUSTC L rust/kernel.o
error[E0425]: cannot find function `krealloc` in module `bindings`
  --> rust/kernel/allocator.rs:17:28
   |
17 |         unsafe { bindings::krealloc(ptr::null(), layout.size(), bindings::GFP_KERNEL) as *mut u8 }
   |                            ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `kfree` in module `bindings`
  --> rust/kernel/allocator.rs:22:23
   |
22 |             bindings::kfree(ptr as *const c_types::c_void);
   |                       ^^^^^ not found in `bindings`

error[E0425]: cannot find function `krealloc` in module `bindings`
  --> rust/kernel/allocator.rs:40:24
   |
40 |     unsafe { bindings::krealloc(core::ptr::null(), size, bindings::GFP_KERNEL) as *mut u8 }
   |                        ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `kfree` in module `bindings`
  --> rust/kernel/allocator.rs:45:24
   |
45 |     unsafe { bindings::kfree(ptr as *const c_types::c_void) };
   |                        ^^^^^ not found in `bindings`

error[E0425]: cannot find function `krealloc` in module `bindings`
  --> rust/kernel/allocator.rs:51:19
   |
51 |         bindings::krealloc(
   |                   ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `krealloc` in module `bindings`
  --> rust/kernel/allocator.rs:62:19
   |
62 |         bindings::krealloc(
   |                   ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `cdev_alloc` in module `bindings`
  --> rust/kernel/chrdev.rs:37:39
   |
37 |         let cdev = unsafe { bindings::cdev_alloc() };
   |                                       ^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `cdev_add` in module `bindings`
  --> rust/kernel/chrdev.rs:62:37
   |
62 |         let rc = unsafe { bindings::cdev_add(self.0, dev, count) };
   |                                     ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `cdev_del` in module `bindings`
  --> rust/kernel/chrdev.rs:74:23
   |
74 |             bindings::cdev_del(self.0);
   |                       ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `alloc_chrdev_region` in module `bindings`
   --> rust/kernel/chrdev.rs:145:27
    |
145 |                 bindings::alloc_chrdev_region(
    |                           ^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `unregister_chrdev_region` in module `bindings`
   --> rust/kernel/chrdev.rs:208:27
    |
208 |                 bindings::unregister_chrdev_region(inner.dev, N.try_into().unwrap());
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `fget` in module `bindings`
  --> rust/kernel/file.rs:26:38
   |
26 |         let ptr = unsafe { bindings::fget(fd) };
   |                                      ^^^^ not found in `bindings`

error[E0425]: cannot find function `fput` in module `bindings`
  --> rust/kernel/file.rs:52:28
   |
52 |         unsafe { bindings::fput(self.ptr) };
   |                            ^^^^ not found in `bindings`

error[E0425]: cannot find function `get_unused_fd_flags` in module `bindings`
  --> rust/kernel/file.rs:98:37
   |
98 |         let fd = unsafe { bindings::get_unused_fd_flags(flags) };
   |                                     ^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `fd_install` in module `bindings`
   --> rust/kernel/file.rs:116:28
    |
116 |         unsafe { bindings::fd_install(self.fd, file.ptr) };
    |                            ^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `put_unused_fd` in module `bindings`
   --> rust/kernel/file.rs:128:28
    |
128 |         unsafe { bindings::put_unused_fd(self.fd) };
    |                            ^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `misc_register` in module `bindings`
  --> rust/kernel/miscdev.rs:75:38
   |
75 |         let ret = unsafe { bindings::misc_register(&mut this.mdev) };
   |                                      ^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `misc_deregister` in module `bindings`
   --> rust/kernel/miscdev.rs:110:32
    |
110 |             unsafe { bindings::misc_deregister(&mut self.mdev) }
    |                                ^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `vm_insert_page` in module `bindings`
  --> rust/kernel/pages.rs:67:38
   |
67 |         let ret = unsafe { bindings::vm_insert_page(vma, address as _, self.pages) };
   |                                      ^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `__free_pages` in module `bindings`
   --> rust/kernel/pages.rs:160:28
    |
160 |         unsafe { bindings::__free_pages(self.pages, ORDER) };
    |                            ^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `strlen` in module `bindings`
  --> rust/kernel/str.rs:96:38
   |
96 |         let len = unsafe { bindings::strlen(ptr) } + 1;
   |                                      ^^^^^^ not found in `bindings`

error[E0425]: cannot find function `slab_is_available` in module `crate::bindings`
   --> rust/kernel/module_param.rs:475:56
    |
475 |         let slab_available = unsafe { crate::bindings::slab_is_available() };
    |                                                        ^^^^^^^^^^^^^^^^^ not found in `crate::bindings`

error[E0425]: cannot find function `printk` in module `bindings`
   --> rust/kernel/print.rs:136:19
    |
136 |         bindings::printk(
    |                   ^^^^^^ not found in `bindings`

error[E0425]: cannot find function `printk` in module `bindings`
   --> rust/kernel/print.rs:155:19
    |
155 |         bindings::printk(
    |                   ^^^^^^ not found in `bindings`

error[E0425]: cannot find function `wait_for_random_bytes` in module `bindings`
  --> rust/kernel/random.rs:16:34
   |
16 |     let res = unsafe { bindings::wait_for_random_bytes() };
   |                                  ^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `get_random_bytes` in module `bindings`
  --> rust/kernel/random.rs:22:19
   |
22 |         bindings::get_random_bytes(
   |                   ^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `rng_is_initialized` in module `bindings`
  --> rust/kernel/random.rs:34:28
   |
34 |     if !unsafe { bindings::rng_is_initialized() } {
   |                            ^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `add_device_randomness` in module `bindings`
  --> rust/kernel/random.rs:45:19
   |
45 |         bindings::add_device_randomness(
   |                   ^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `prepare_to_wait_exclusive` in module `bindings`
  --> rust/kernel/sync/condvar.rs:77:23
   |
77 |             bindings::prepare_to_wait_exclusive(
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `schedule` in module `bindings`
  --> rust/kernel/sync/condvar.rs:88:28
   |
88 |         unsafe { bindings::schedule() };
   |                            ^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `finish_wait` in module `bindings`
  --> rust/kernel/sync/condvar.rs:93:28
   |
93 |         unsafe { bindings::finish_wait(self.wait_list.get(), wait.as_mut_ptr()) };
   |                            ^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `__wake_up` in module `bindings`
   --> rust/kernel/sync/condvar.rs:102:23
    |
102 |             bindings::__wake_up(
    |                       ^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `__init_waitqueue_head` in module `bindings`
   --> rust/kernel/sync/condvar.rs:135:28
    |
135 |         unsafe { bindings::__init_waitqueue_head(self.wait_list.get(), name.as_char_ptr(), key) };
    |                            ^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `__mutex_init` in module `bindings`
  --> rust/kernel/sync/mutex.rs:76:28
   |
76 |         unsafe { bindings::__mutex_init(self.mutex.get(), name.as_char_ptr(), key) };
   |                            ^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `mutex_unlock` in module `bindings`
  --> rust/kernel/sync/mutex.rs:95:28
   |
95 |         unsafe { bindings::mutex_unlock(self.mutex.get()) };
   |                            ^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `register_sysctl` in module `bindings`
   --> rust/kernel/sysctl.rs:161:41
    |
161 |         let result = unsafe { bindings::register_sysctl(path.as_char_ptr(), table.as_mut_ptr()) };
    |                                         ^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `unregister_sysctl_table` in module `bindings`
   --> rust/kernel/sysctl.rs:182:23
    |
182 |             bindings::unregister_sysctl_table(self.header);
    |                       ^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `iov_iter_zero` in module `bindings`
  --> rust/kernel/iov_iter.rs:62:46
   |
62 |             let written = unsafe { bindings::iov_iter_zero(len, self.ptr) };
   |                                              ^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `__platform_driver_register` in module `bindings`
  --> rust/kernel/platdev.rs:85:38
   |
85 |         let ret = unsafe { bindings::__platform_driver_register(&mut this.pdrv, module.0) };
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `platform_driver_unregister` in module `bindings`
   --> rust/kernel/platdev.rs:113:32
    |
113 |             unsafe { bindings::platform_driver_unregister(&mut self.pdrv) }
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `kernel_param_lock` in module `bindings`
   --> rust/kernel/lib.rs:131:23
    |
131 |             bindings::kernel_param_lock(self.0)
    |                       ^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `kernel_param_unlock` in module `bindings`
   --> rust/kernel/lib.rs:151:28
    |
151 |         unsafe { bindings::kernel_param_unlock(self.this_module.0) }
    |                            ^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error: aborting due to 42 previous errors

For more information about this error, try `rustc --explain E0425`.
make[1]: *** [rust/Makefile:212: rust/kernel.o] Error 1
```

</p>
</details>

**Comment by ojeda** [comment]
Thanks for testing it! We should have a CI test for ThinLTO (or perhaps enable it by default and have just one without LTO).

Let me fold the output in your post (see the edit I will do, you can use it elsewhere for big logs etc.).

**Comment by TheSven73** [comment]
Same issue happens on `v5.13`.

**Comment by sodar** [comment]
Hi! I just started looking into the issue. I'll let you all know if I manage to fix it as soon as I can.

**Comment by nbdd0121** [comment]
It's likely that fixing this only requires filtering out LTO-related flags when passing clang flags to bindgen.
