### PR TITLE
rust: add `IoMem` abstraction.

### PR DESCRIPTION
**Pull request by wedsonaf**
This is based on what I described in LKML
(https://lore.kernel.org/lkml/YIbQ3dHOpyD%2FyymW@google.com/) back in
April.

This is in preparation for the PL061 driver to be merged.

Signed-off-by: Wedson Almeida Filho <wedsonaf@google.com>

### CODE REVIEW

File: rust/kernel/io_mem.rs [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+macro_rules! define_write {
+    ($name:ident, $try_name:ident, $type_name:ty) => {
+        /// Writes IO data to the given offset, known at compile time.
+        ///
+        /// If the offset is not known at compile time, the build will fail.
+        pub fn $name(&self, value: $type_name, offset: usize) {
+            Self::check_offset::<$type_name>(offset);
+            let ptr = self.ptr.wrapping_add(offset);
+            // SAFETY: The type invariants guarantee that `ptr` is a valid pointer. The check above
+            // guarantees that the code won't link if `offset` makes the write go out of bounds
```
Comment (ojeda) [inline rust/kernel/io_mem.rs:119]: Nit: a more generic way to say it (which also matches the doc above and does not depend on how `build_error!` is implemented):

```suggestion
            // guarantees that the code won't build if `offset` makes the write go out of bounds
```

File: rust/kernel/io_mem.rs [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+    /// accessed directly. It is also consumed by this function so that it can't be mapped again
+    /// to a different address.
+    pub fn try_new(res: Resource) -> Result<Self> {
+        // Check that the resource has at least `SIZE` bytes in it.
+        if res.size < SIZE.try_into()? {
+            return Err(Error::EINVAL);
+        }
+
+        // Try to map the resource.
+        // SAFETY: Just mapping the a memory range.
```
Comment (bjorn3) [inline rust/kernel/io_mem.rs]: s/a//
maybe also mention that it is guaranteed to only be mapped once.

File: rust/kernel/io_mem.rs [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+pub struct Resource {
+    offset: bindings::resource_size_t,
+    size: bindings::resource_size_t,
+}
+
+impl Resource {
+    pub(crate) fn new(
+        start: bindings::resource_size_t,
+        end: bindings::resource_size_t,
+    ) -> Option<Self> {
```
Comment (ojeda) [inline rust/kernel/io_mem.rs:37]: Should this be `Result`? i.e. if the callers pass the wrong arguments, it is supposed to be an error, or does the notion of a "no resource" make sense for some use cases?

File: rust/kernel/io_mem.rs [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+        }
+    };
+}
+
+macro_rules! define_write {
+    ($name:ident, $try_name:ident, $type_name:ty) => {
+        /// Writes IO data to the given offset, known at compile time.
+        ///
+        /// If the offset is not known at compile time, the build will fail.
+        pub fn $name(&self, value: $type_name, offset: usize) {
```
Comment (bjorn3) [inline rust/kernel/io_mem.rs:115]: Would it be possible to make `offset` a const generic? That way `Self::check_offset` can be evaluated at compile time and thus work even with optimizations disabled or with `#[inline]` on this function.

File: rust/kernel/io_mem.rs [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+}
+
+/// Represents a memory resource.
+pub struct Resource {
+    offset: bindings::resource_size_t,
+    size: bindings::resource_size_t,
+}
+
+impl Resource {
+    pub(crate) fn new(
```
Comment (bjorn3) [inline rust/kernel/io_mem.rs:34]: This should be `unsafe`, right? `IoMem` depends on the fact that you can't duplicate a `Resource`.

File: rust/kernel/io_mem.rs (hunk 4 above)
Comment (ojeda) [reply rust/kernel/io_mem.rs:115]: I assume someone will eventually ask for the non-const-generic-but-known-at-compile-time case (e.g. zeroing some register table using a loop). Or is there an easy way (i.e. without macros to unfold manually etc.) to e.g. use the index of a `for` loop within a static range to call a const generic?

File: rust/kernel/io_mem.rs (hunk 3 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:37]: It is possible for a device implementation(of a spec) not to have some optional register bank. I don't think we have enough information to decide what the appropriate error should be, so making this an `Option` we push the decision to the caller.

File: rust/kernel/io_mem.rs (hunk 4 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:115]: I like the improvements we'd get, but I think the ergonomics wouldn't be good: to call it, we would need to do something like `mem.writeb::<X>(v)`, which is quite a mouthful and also changes the order of arguments when compared to C. This would be giving more ammunition to those unhappy with Rust with marginal extra benefit (when used correctly).

File: rust/kernel/io_mem.rs (hunk 3 above)
Comment (ojeda) [reply rust/kernel/io_mem.rs:37]: I was thinking more about the `checked_*` operations, not so much about `start == 0`.

File: rust/kernel/io_mem.rs [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+    };
+}
+
+impl<const SIZE: usize> IoMem<SIZE> {
+    /// Tries to create a new instance of a memory block.
+    ///
+    /// The resource described by `res` is mapped into CPU's address space so that it can be
+    /// accessed directly. It is also consumed by this function so that it can't be mapped again
+    /// to a different address.
+    pub fn try_new(res: Resource) -> Result<Self> {
```
Comment (nbdd0121) [inline rust/kernel/io_mem.rs]: Shouldn't this be unsafe? The caller needs to guarantee that it "owns" the resource that `Resource` describes.

File: rust/kernel/io_mem.rs [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+                return true;
+            }
+        }
+        false
+    }
+
+    const fn check_offset<T>(offset: usize) {
+        if !Self::offset_ok::<T>(offset) {
+            crate::build_error!("IoMem offset overflow");
+        }
```
Comment (nbdd0121) [inline rust/kernel/io_mem.rs]:
```suggestion
        crate::build_assert!(Self::offset_ok::<T>(offset), "IoMem offset overflow");
```

File: rust/kernel/io_mem.rs [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+    }
+
+    define_read!(readb, try_readb, u8);
```
Comment (nbdd0121) [inline rust/kernel/io_mem.rs:193]: How about just name them `read_u8, read_u16, read_u32, read_u64`?

File: rust/kernel/io_mem.rs [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+        /// Reads IO data from the given offset known, at compile time.
+        ///
+        /// If the offset is not known at compile time, the build will fail.
+        pub fn $name(&self, offset: usize) -> $type_name {
+            Self::check_offset::<$type_name>(offset);
+            let ptr = self.ptr.wrapping_add(offset);
+            // SAFETY: The type invariants guarantee that `ptr` is a valid pointer. The check above
+            // guarantees that the code won't link if `offset` makes the read go out of bounds
+            // (including the type size).
+            unsafe { concat_idents!(rust_helper_, $name)(ptr as _) }
```
Comment (nbdd0121) [inline rust/kernel/io_mem.rs:91]: Off-topic: Would be great if we have a `paste`-like macro

**Review by nbdd0121 — COMMENTED** [review]
General API design question: do we want `readb`/`read_u8` or `read::<u8>()`?

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: Also, the IO memory mapped cannot trigger any DMA operation, otherwise DMA could be used to safely circumvent all Rust safety measures.

File: rust/kernel/io_mem.rs (hunk 5 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:34]: I don't think `IoMem` depends on this for safety. Having the same range mapped multiple times should be ok; it may be bad for correctness, but why would it violate safety? We never use the returned pointer directly in Rust, only as arguments to readX/writeX.

I'm more concerned about the DMA case. My thinking was to make the DMA interface unsafe, but now that Gary mentioned it, it occurs to me that even a DMA "handle" is just a number that could be written to a device. IOW, what forces a driver to go through the unsafe DMA interface when it could just encode some arbitrary physical address and ask a bus mastering device to read/write it? Nothing at the moment, so this needs more thought.

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: It's taking over the the resource. And the resource doesn't have a public constructor.

File: rust/kernel/io_mem.rs (hunk 8 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:193]: No, the names were chosen to match those of the kernel.

Comment (nbdd0121) [reply rust/kernel/io_mem.rs:193]: Well, it's not always best to name them exactly as C does. `try_write_u32` certainly feels a lot more Rust-y than `try_writel`.

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: > Also, the IO memory mapped cannot trigger any DMA operation, otherwise DMA could be used to safely circumvent all Rust safety measures.

Of course we want drivers to be able to start DMA operations through this. What would the point of not allowing that?

The question is: how can we restrict this? My thinking was to leave DMA allocation safe, but getting a "handle" (that would be passed to a device for DMA) to the allocation would be unsafe with the restriction that the allocation should be kept alive until the device completed the DMA. (There's no way for us to know when a device is done, so this operation seems intrinsically unsafe.)

The problem with the strategy above is that a driver could write anything to the device, including arbitrary values as DMA handles, and that could of course violate memory safety. I suppose we could make this function unsafe with the requirement that callers need to be careful with DMA, but that's a big hammer and would make this function unnecessarily unsafe for devices like gpio that are not bus-mastering.

Any other ideas?

File: rust/kernel/io_mem.rs (hunk 3 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:37]: Are you proposing that we return `Result<Option<Self>>` or `Result<Self>`?

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: I don't think it's too big an issue to make this function unsafe. A GPIO driver would only need to say: `// SAFETY: This device cannot perform DMA`.

File: rust/kernel/io_mem.rs (hunk 8 above)
Comment (nbdd0121) [reply rust/kernel/io_mem.rs:193]: I just made a mistake writing `writew` rather than `writel`; this is because RISC-V uses `b/h/w/d` while kernel uses `b/w/l/q` and I confused myself. One reason to prefer `u8/u16/u32/u64`!

Comment (wedsonaf) [reply rust/kernel/io_mem.rs:193]: I'm not claiming it's _always_ best. I'm claiming that this was an explicit and conscious choice for this interface. The idea is to reduce friction when writing drivers similar to existing C ones; in case you haven't seen it yet, here's the converted PL061 GPIO driver: https://lwn.net/Articles/863459/

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: Sure, but it's still a big hammer for bus-mastering devices though: "you need to be disciplined while programming operations involving DMA" is not very Rust-like, we'd be basically reverting to C mode and leaving it up to developers to ensure safety. I don't like that.

Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: It's up to the author of DMA-capable devices to ensure that all DMA operations are correct, and I don't think it could be checked. The best we can do is a separate `IoMem` that is safe to create but unsafe to access.

File: rust/kernel/io_mem.rs (hunk 8 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:193]: > I just made a mistake writing `writew` rather than `writel`; this is because RISC-V uses `b/h/w/d` while kernel uses `b/w/l/q` and I confused myself. One reason to prefer `u8/u16/u32/u64`!

I'm sorry to hear that.

However, as discussed in the past: our target audience is kernel developers. At least for now, when we have to make a choice between being clearer for Rust or kernel developers, we'll choose kernel developers.

Comment (ojeda) [reply rust/kernel/io_mem.rs:193]: Gary, this is Linux code, not Rust code. Whether the names feel "Rust-y" or not is not really important -- what current kernel developers feel is. We need to be mindful of introducing naming changes in very well-known APIs, specially if the example driver is going to be compared with the C version side-by-side.

I prefer names like `_u32` myself too, but just because I think seeing the type is simpler. While it is tempting to improve naming, it should be discussed with others when we are in mainline, not before and on our own.

Comment (nbdd0121) [reply rust/kernel/io_mem.rs:193]: Well, my confusion comes from the fact that I work with assembly and hardware, not that I am a Rust developer. I don't think it's really a friction for kernel developers to switch to `u8/u16/u32/u64`: they could easily understand that. Using `u8/u16/u32/u64` has an additional advantage that it's less friction for  new developers and people who work on lower levels that uses a different convention for sizes. I don't really see much advantage for keep using x86-centric `bwlq` convention.

File: rust/kernel/io_mem.rs (hunk 6 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: I suppose we could make the safety requirement be that either (a) no DMA operations are performed, or (b) DMA buffers should be retrieved via the `dma` module (which will have further requirements).

Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: Well, regardless how DMA buffers are retrieved, it's still up to the device to ensure that correct address is written isn't it?

Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: It's up to the driver, yes.

But if we make the DMA "get handle" interface unsafe and require developers to go through it, we force them to consider the safety requirements then (when programming an operation). My feeling is that having the safety requirement only in `IoMem::try_new` that is buried in init code rarely looked at will allow developers to violate them without noticing it -- not too different from C.

Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: Maybe use macros to generate register maps would be the best approach for safety; some registers could be marked unsafe with this approach. E.g.
```rust
iomap! {
	unsafe PL061IoMem {
		  gpiodir: u8 @ 0x400,
		  gpiois: u8 @ 0x404,
		  gpiobe: u8 @ 0x408,
		  gpioiev: u8 @ 0x40C,
		  gpioie: u8 @ 0x410,
		  gpiomis: u8 @ 0x418,
		  gpioic: u8 @ 0x41C,
	}
}
```
and then for a DMA device a register could be written as
```rust
		unsafe dma_addr: u64 @ ...,
```

Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: I like where this is going. It also goes well with Miguel's idea of automatically generating accessors for individual registers.

One problem with this approach is that we don't always encode the dma address via IO mem like this. For example, in the NVMe case, we use host memory to hold command queues -- the entries in these queues hold DMA addresses, and IO mem is only a doorbell to indicate that new entries have been added to queues.

Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: I have no experience with NVMe but from your description it is does not sound very different from how virtio queue works. The command queue setup registers could be made unsafe in that case, and it's then up to the command queue abstraction to propagate the safety requirements.

File: rust/kernel/io_mem.rs (hunk 2 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: Fixed.

File: rust/kernel/io_mem.rs (hunk 1 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:119]: Fixed.

File: rust/kernel/io_mem.rs (hunk 7 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: Better indeed, thanks!

**Comment by wedsonaf** [comment]
### v1 -> v2

* Rebased
* Fixed build break on 32-bit archs (missing readq/writeq).
* Updated wording on comment (link vs build).
* Made `IoMem::try_new` unsafe.
* Fixed typo in safety comment when calling `rust_helper_ioremap`.
* Use `build_assert!` instead of `if !x { build_error!(...) }`.

**Comment by wedsonaf** [comment]
@ojeda -- it looks like `ctypes::u_long` for arm (32 bits) is mapped to `u32` when building the kernel but `u64` in `rusttest`. The kernel builds fine, but `rusttest` is failing with the following (from https://github.com/Rust-for-Linux/linux/pull/462/checks?check_run_id=3196992364):

```
error[E0308]: mismatched types
   --> rust/kernel/io_mem.rs:161:61
    |
161 |         let addr = unsafe { rust_helper_ioremap(res.offset, res.size) };
    |                                                             ^^^^^^^^
    |                                                             |
    |                                                             expected `u64`, found `u32`
    |                                                             help: you can convert a `u32` to a `u64`: `res.size.into()`

error: aborting due to previous error
```

With `rust_helper_ioremap` defined as:

```
    fn rust_helper_ioremap(
        offset: bindings::resource_size_t,
        size: c_types::c_ulong,
    ) -> *mut c_types::c_void;
```

Is this expected? (Or am I misreading the error?)

File: rust/kernel/io_mem.rs (hunk 3 above)
Comment (ojeda) [reply rust/kernel/io_mem.rs:37]: If `start == 0` is expected but bad arguments are not, then `Result<Option<Self>>` might be the right fit semantically, yeah.

File: rust/kernel/io_mem.rs [hunk 10]
```diff
@@ -0,0 +1,200 @@
...
+            Err(Error::ENOMEM)
+        } else {
+            // INVARIANT: `addr` is non-null and was returned by `ioremap`, so it is valid.
+            Ok(Self { ptr: addr as usize })
+        }
+    }
+
+    const fn offset_ok<T>(offset: usize) -> bool {
+        if let Some(end) = offset.checked_add(core::mem::size_of::<T>()) {
+            if end <= SIZE {
```
Comment (fbq) [inline rust/kernel/io_mem.rs]: I'm not 100% sure, but those `readX()` and `writeX()` seems to require the address being naturally aligned (i.e. aligned to the size of read and write), find something in the doc: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/driver-api/device-io.rst#n327

Won't hurt to get this clear.

File: rust/kernel/io_mem.rs (hunk 3 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs:37]: This is an internal API, used here: https://github.com/wedsonaf/linux/blob/pl061/rust/kernel/amba.rs#L174

I don't think making it `Result<Option<Self>>` is necessary because we don't surface this to developers, and I don't think we want to fail `probe` before even giving drivers a chance to run.

File: rust/kernel/io_mem.rs (hunk 10 above)
Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: Are you proposing that we check for natural alignment?

If it isn't a requirement for all platforms, I don't think we can do it here.

Comment (fbq) [reply rust/kernel/io_mem.rs]: > Are you proposing that we check for natural alignment?
> 

Yes, that's what's in my mind.

> If it isn't a requirement for all platforms, I don't think we can do it here.

I understand your point, but without the natural alignment checks, the Rust version `readX()` and `writeX()` seems `unsafe` to me.

Comment (fbq) [reply rust/kernel/io_mem.rs]: > > If it isn't a requirement for all platforms, I don't think we can do it here.
> 
> I understand your point, but without the natural alignment checks, the Rust version `readX()` and `writeX()` seems `unsafe` to me.

Except that `readb` and `writeb` are `safe`.

**Comment by wedsonaf** [comment]
> @ojeda -- it looks like `ctypes::u_long` for arm (32 bits) is mapped to `u32` when building the kernel but `u64` in `rusttest`. The kernel builds fine, but `rusttest` is failing with the following (from https://github.com/Rust-for-Linux/linux/pull/462/checks?check_run_id=3196992364):

Opened #465 for this.

File: rust/kernel/io_mem.rs (hunk 10 above)
Comment (nbdd0121) [reply rust/kernel/io_mem.rs]: > If it isn't a requirement for all platforms, I don't think we can do it here.

If it's a requirement for any platform, the driver shouldn't depend on it. Perhaps we should offer an `_unchecked` variant, and who uses it need to prove that they won't ever be ran on platforms without misalignment memory access support.

Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: The document linked clearly states that "on many platforms" this is a requirements. Not all.

But I do like the idea of offering two versions. I'll make this one this the checked one, and we can add an unchecked one in the future if/when we find a case where we need this.

Comment (fbq) [reply rust/kernel/io_mem.rs]: Note that the link is the only evidence I found talking about the alignment requirement, and actually it was added just recently in this [patch](https://lore.kernel.org/lkml/20210402090542.131194-10-marcan@marcan.st/), I don't find many reviews on the doc. `readX()` and `writeX()` are heavily used APIs in kernel, I'd expect there are a few places (e.g. comments or docs) saying the requirement, but I only find one.

**Comment by wedsonaf** [comment]
### v2 -> v3

* Added alignment check

**Comment by wedsonaf** [comment]
### v3 -> v4

* Worked around #465

File: rust/kernel/io_mem.rs (hunk 10 above)
Comment (fbq) [reply rust/kernel/io_mem.rs]: FWIW, send an [email](https://lore.kernel.org/linux-arch/YQQr+twAYHk2jXs6@boqun-archlinux/T/#u) to linux-arch for some clarification.

Comment (ojeda) [reply rust/kernel/io_mem.rs]: > If it's a requirement for any platform, the driver shouldn't depend on it. Perhaps we should offer an `_unchecked` variant, and who uses it need to prove that they won't ever be ran on platforms without misalignment memory access support.

We could provide a safe one that only exists in the platforms where it is so -- that way people can freely use it for platform-dependent drivers, and if someone ever tries to copy-paste the code or port the module to another platform, they would get an error.

Comment (wedsonaf) [reply rust/kernel/io_mem.rs]: What we have now: a version with an unadorned name that checks alignment -- it is safe (in that it doesn't require an `unsafe` block and doesn't issue unaligned reads/writes) for anyone to use, but they'll get an error if they try some unaligned operation.

If we ever find a device whose driver requires unaligned access, we can add an unsafe version (whose name will be suffixed with `_unchecked`) that doesn't have the alignment check, and whose callers must be convinced that it is safe.
